### ISSUE TITLE
add options for decryption-provider & decryption-secret to flux_sync

### ISSUE THREAD

**Issue by haraldatbmw** [fluxcd/terraform-provider-flux#103]
Terraform-provider-flux should create a `gotk-sync.yaml` file with **decryption-provider** and **secret-reference** inside.
Like the flux cli does - see https://toolkit.fluxcd.io/cmd/flux_create_kustomization/

**actual**
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
```

**expected**
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m0s
  path: ./clusters/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
```
