### ISSUE TITLE
Customize Flux manifests feature request

### ISSUE THREAD

**Issue by nuriel77** [fluxcd/terraform-provider-flux#146]
Since fluxcd/flux2 version 0.13.1 it is possible to add Customize Flux manifests. 
See: https://github.com/fluxcd/flux2/blob/v0.13.1/docs/guides/installation.md#customize-flux-manifests
And ref PR: https://github.com/fluxcd/flux2/pull/1300
Example:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patchesStrategicMerge:
  - gotk-patches.yaml
```

Is it currently possible to append last 2 lines to flux_sync in any way? (maybe somehow in terraform the lines can be appended to the yaml?)
