### ISSUE TITLE
Missing RBAC for CRDs in 0.3.1 on 1.19.x k8s

### ISSUE THREAD

**Issue by sharkymcdongles** [fluxcd/terraform-provider-flux#192]
My automation uses this provider to manage flux via Terraform in all our environments. I just created a new cluster today and encountered a new error:

```
creating 1 resource(s)
  Normal  error  7m19s (x3 over 17m)  helm-controller  reconciliation failed: Helm install failed: failed to install CRD crds/backups.yaml: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:flux-system:helm-controller" cannot create resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope

```

When I check the RBAC I see the provider creates this role:

```
rules:
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - notification.toolkit.fluxcd.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - image.toolkit.fluxcd.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  - configmaps/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
```

It seems this role needs the ability to create, delete, and edit CRDs added to work. I am not sure what changed between versions to require this now.
