### ISSUE TITLE
`patchesStrategicMerge` deprecated in Flux 2

### ISSUE THREAD

**Issue by tobiasehlert** [fluxcd/terraform-provider-flux#333]
Hi,

I'm looking for a way to add customizations to my _kustomize.yaml_ file generated by this Terraform provider.

Starting with v0.18 of Flux 2, the _kustomize.toolkit.fluxcd.io/v1beta2_ API was updated and in combination with that, the `.spec.patchesStrategicMerge` was deprecated in favour of `.spec.patches`.

How can we run this Terraform provider so that we can use the `.spec.patches` instead of `.spec.patchesStrategicMerge`?

Here is the link to the discussion about upgrade of Flux to the Kustomize v1beta2 API:
https://github.com/fluxcd/flux2/discussions/1916#discussion-3616377

I know there is another issue open (#231) that talks about a similar thing, but created a separate one due to the deprecation part.

---

As for my case, I'd like to drop some particular value (that makes Flux to fail in OpenShift) and to increase the memory settings of the containers.

Here is what I'd like to see as a result:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            containers:
              - name: manager
                securityContext:
                  runAsUser: 65534
                  seccompProfile:
                    $patch: delete
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux

  - target:
      kind: Deployment
      name: helm-controller
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ignored
      spec:
        template:
          spec:
            containers:
            - name: manager
              resources:
                limits:
                  memory: 3Gi
                requests:
                  memory: 1Gi
```
