### ISSUE TITLE
Source Controller unable to clone  when bootstrapped using Terraform 

### ISSUE THREAD

**Issue by winniegakuru** [fluxcd/terraform-provider-flux#334]
Hi,
I am getting a particularly odd outcome when I bootstrap an EKS cluster using Terraform. I get the error below:

```
level":"error","ts":"2022-10-21T14:39:53.699Z","msg":"Reconciler error","controller":"gitrepository","controllerGroup":"source.toolkit.fluxcd.io","controllerKind":"GitRepository","GitRepository":{"name":"flux-system","namespace":"flux-system"},"namespace":"flux-system","name":"flux-system","reconcileID":"b7ddf3e2-2990-4295-a3f8-cd6732bbdb16","error":"failed to checkout and determine revision: unable to clone 'https://gitlab.xxxxxxx.com/dev/fluxv2/xxxxxx.git': authentication required
```

This is the flux version installed 

``` 
This manifest was generated by flux. DO NOT EDIT.
Flux Version: v0.35.0
 Components: source-controller,kustomize-controller,helm-controller,notification-controller,image-reflector-controller,image-automation-controller
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v0.35.0
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
  name: flux-system
.....
```
Flux secret was created successfully.
```
>>>>>(main) $ kubectl -n flux-system get secrets
NAME                                      TYPE                                  DATA   AGE
default-token-flncz                       kubernetes.io/service-account-token   3      52m
flux-system                               Opaque                                2      52m
helm-controller-token-4nsdw               kubernetes.io/service-account-token   3      52m
image-automation-controller-token-4679s   kubernetes.io/service-account-token   3      52m
image-reflector-controller-token-6p5pg    kubernetes.io/service-account-token   3      52m
kustomize-controller-token-52kwk          kubernetes.io/service-account-token   3      52m
notification-controller-token-sz74d       kubernetes.io/service-account-token   3      52m
source-controller-token-8kttr             kubernetes.io/service-account-token   3      52m
```

NB:
Bootstrapping through CLI works very well using the same Gitlab PAT:

I also had bootstrapped another cluster using terraform ( Flux v0.30.2 component manifests) And it was successful.
Not sure if it is a version issue.
