### ISSUE TITLE
There doesn't seem to be a way to disable the secret attribute

### ISSUE THREAD

**Issue by ralgar** [fluxcd/terraform-provider-flux#339]
## Problem

There doesn't seem to be any way to disable the secret attribute when rendering templates with the `flux_sync` data source. This prevents the user from easily configuring this provider without a deploy key, for a public repository. I've tried setting the value of `secret` to `null`, which leaves the rendered `secretRef.name` value as the default `flux-system`. I've also tried setting the value to `false`, which oddly enough actually renders a secretRef named `false`.

```
# sync.tf
data "flux_sync" "main" {
  url         = var.gitops_repo
  branch      = var.gitops_branch
  target_path = var.gitops_path
  secret      = false
}
```

```
# Rendered GitRepository object
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: "false"
  timeout: 60s
  url: https://github.com/user/repo.git
```

This leads to errors, as Flux is trying to search for a deploy key that isn't needed, and doesn't exist.

## Proposal

Explicitly setting the parameter to `null` and/or `false` (I think it may have to be the latter) should disable the attribute entirely, rendering a manifest like so:

```
# Fixed GitRepository object
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: master
  timeout: 60s
  url: https://github.com/user/repo.git
```

This would allow a user to easily configure this provider without a deploy key, for a public repository.
