### ISSUE TITLE
Fail to import flux bootstrap

### ISSUE THREAD

**Issue by mikkoc** [fluxcd/terraform-provider-flux#392]
I'm trying to import our existing flux installation into Terraform.

flux provider is 0.24.2

```
resource "flux_bootstrap_git" "this" {
  depends_on = [github_repository_deploy_key.this]

  url  = "ssh://git@github.com/mycompany/myrepo.git"
  path = "clusters/${var.environment}"
  ssh = {
    username    = "git"
    private_key = tls_private_key.this.private_key_pem
  }
  version = "v0.39.0"
  components_extra = [
    "image-automation-controller",
    "image-reflector-controller"
    ]
}
```

And this is the error:

```
 $ terraform import flux_bootstrap_git.this flux-system
╷
│ Error: Getting expected repository files
│
│ Could not generate install manifests: accumulating resources: accumulation err='merging resources from 'helm-controller.yaml': may not add resource with an already registered
│ id: CustomResourceDefinition.v1.apiextensions.k8s.io/helmreleases.helm.toolkit.fluxcd.io.[noNs]': must build at directory:
│ '/private/var/folders/5w/v7ykq4fn74d8dx52f_zgdl600000gn/T/flux-system72758367/helm-controller.yaml': file is not directory
╵

Releasing state lock. This may take a few moments...
```

**Comment by phillebaba** [comment]
This seems identical to #384, might be good to figure out what is in common. From where is this `helm-controller.yaml` file generated from?

**Comment by mikkoc** [comment]
I am not entirely sure. I had just installed Flux a few weeks ago using the boostrap command. 

```
flux bootstrap github --components-extra=image-reflector-controller,image-automation-controller --owner=mycompany --repository=myrepo --path=clusters/my-env --read-write-key --verbose
```

What can I provide to debug further?

**Comment by mikkoc** [comment]
I have found the helm-controller CRD definition in the repo, path: `myrepo/clusters/my-cluster/flux-system/gotk-components.yaml` , snippet here:

```
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: helm-controller
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v0.39.0
  name: helmreleases.helm.toolkit.fluxcd.io
spec:
  group: helm.toolkit.fluxcd.io
  names:
    kind: HelmRelease
    listKind: HelmReleaseList
    plural: helmreleases
    shortNames:
    - hr
    singular: helmrelease
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].message
      name: Status
      type: string
    name: v2beta1
    schema:
```
