### ISSUE TITLE
Provider removing kustomize-controller patch

### ISSUE THREAD

**Issue by adeturner** [fluxcd/terraform-provider-flux#478]
Thanks for the prior help.

Implementing SOPS/AAD pod identity, I'm not sure the best way to patch the kustomize-controller so have put it in clusters/staging/flux-system/kustomization.yaml.  This did match the approach in the docs [https://fluxcd.io/flux/installation/#customize-flux-manifests](https://fluxcd.io/flux/installation/#customize-flux-manifests)

Having done that I've found that rerunning the terraform provider 1.0.0-rc3 is reverting kustomization.yaml and wiping out my patch

Note: the lines matching ^*** are removals:

```txt
  # flux_bootstrap_git.this will be updated in-place
  ~ resource "flux_bootstrap_git" "this" {
        id                   = "flux-system"
      ~ repository_files     = {
          ~ "clusters/staging/flux-system/kustomization.yaml"   = <<-EOT
                apiVersion: kustomize.config.k8s.io/v1beta1
                kind: Kustomization
                resources:
                - gotk-components.yaml
                - gotk-sync.yaml
***                - patches:
***                - - path: kustomize-controller-patch.yaml            
            EOT
            # (2 unchanged elements hidden)
        }
        # (11 unchanged attributes hidden)
    }
```

fyi...

```txt
 $ find clusters/staging/

clusters/staging/flux-system
clusters/staging/flux-system/kustomization.yaml
clusters/staging/flux-system/kustomize-controller-patch.yaml
clusters/staging/flux-system/gotk-sync.yaml
clusters/staging/flux-system/gotk-components.yaml
clusters/staging/infrastructure.yaml
clusters/staging/apps.yaml
```

kustomization.yaml:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
- path: kustomize-controller-patch.yaml
```

kustomize-controller-patch.yaml:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app: kustomize-controller
  template:
    metadata:
      labels:
        ## For aad-pod-identity
        # aadpodidbinding: ${IDENTITY_NAME} match the AzureIdentity name
        aadpodidbinding: sops-decryptor
    spec:
      containers:
      - name: manager
        ## For aad-pod-identity
        env:
        - name: AZURE_AUTH_METHOD
          value: msi
```
