### ISSUE TITLE
gotk-sync.yaml gets newer CRD version when using older version of flux

### ISSUE THREAD

**Issue by defenestration** [fluxcd/terraform-provider-flux#493]
Hello, I was adding a new cluster to our terraform setup ( we have multiple clusters created from the same terraform root module ) and I lock the flux version on those clusters. However I bumped up the flux terraform provider module to 1.0.0-rc.5 to work around an issue, and notice this causes the gotk-sync.yaml in the clusters that I set the version of flux to 0.41.2, since it updates the API version of those resources. 

It looks like I can just define an aliased provider with the different versions in terraform [like this](https://stackoverflow.com/a/66430076) so I am looking into that, but wonder if there is a way to work it into the module to offer a smooth transition?

In the old flux versions, these resource in gotk-sync.yaml should be `v1beta2` api version. 

```
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
...
```
