### ISSUE TITLE
Allow bootstrapping of additional resources to the flux-system namespace

### ISSUE THREAD

**Issue by v0lkc** [fluxcd/terraform-provider-flux#536]
`flux_bootstrap_git` allows users to override the `kustomization.yaml` file using the `kustomzation_override` parameter. This is really handy, but doesn't go far enough. In addition users should be allowed to bring in additional resource definitions to the flux-system namespace.

E.g. we're using [istio](https://istio.io) in our k8s clusters and want to enable it for the flux controllers too. For that we need to
1. add a label to the `flux-system` namespace (`istio-injection: enabled`).
2. bring in a `VirtualService` definition for the SourceController. Without this definition, flux is unable to reconcile and the bootstrapper ends in an timeout.

The first point is already supported, but the second is not. The `kustomization_override` would effectively look like this:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |- # <== enables istio in the flux-system namespace (1.)
    - op: add 
      path: /metadata/labels/istio-injection
      value: enabled
  target:
    kind: Namespace
    name: flux-system
resources:
- gotk-components.yaml
- gotk-sync.yaml
- gotk-istio-virtualservice.yaml # <== adds a virtualservice definition for the SourceController (2.)
```

**Comment by v0lkc** [comment]
Ok, I figured out a nice way to solve this, which doesn't require a modification of the terraform provider. It completely relies on the capabilities of kustomize. You can basically import other kustomazation files with the `bases` attribute.

With that my override looks now like this:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../_base/flux-system/
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
- patch: |-
    - op: add 
      path: /metadata/labels/istio-injection
      value: enabled
  target:
    kind: Namespace
    name: flux-system
```

And in `/clusters/_base/flux-system/` there's a different kustomization file which introduces the virtualservice for istio:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-istio-virtualservice.yaml
```
