### ISSUE TITLE
Patch GitRepository using flux_bootstrap_git

### ISSUE THREAD

**Issue by anupclouddevops** [fluxcd/terraform-provider-flux#556]
We are currently using terraform provider v0.21.0 and planning to upgrade to latest bootstrap resource.
In old version, we enabled GPG verification for GitRepository resource using patch_names field in flux_sync resource

`data "flux_sync" "main" {
  target_path = var.gitops_repo_target_path
  url         = "ssh://git@github.com/${var.github_organization}/${var.repository_name}.git"
  patch_names = keys(local.gpg_patch_file)
}`

`gpg_patch_file = var.gpg_enabled ? { gpg-commit-verification = ["${path.module}/data/patch-gpg-commit-verification.yaml"] } : {}`

data/patch-gpg-commit-verification.yaml is :
`apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  verify:
    mode: head
    secretRef:
      name: flux-gpg-pubkeys`

However, there seems to be no option available to apply patch on `GitRepository` resource in `flux_bootstrap_git` resource.
If we add the patch in `kustomization.yaml` then `gotk-sync.yaml` pushed is blank and the provider gives an error that it's unable to find GitRepository resource in Kubernetes to patch and the whole bootstrap fails.

Please look into this on priority as we are blocked because of this.

Thanks for your support

**Comment by stefanprodan** [comment]
The GitRepository API in now GA, the patch should target `source.toolkit.fluxcd.io/v1`. Please see the migration guide from 0.x to 2.x https://github.com/fluxcd/flux2/releases/tag/v2.0.0#upgrade

**Comment by anupclouddevops** [comment]
@stefanprodan , I know the same patch target should be source.toolkit.fluxcd.io/v1. 

But where should this patch be specified. 

There are no sync manifests exposed in new bootstrap resource `flux_bootstrap_git` and if I specify the patch in `kustomize_override` ,g the bootstrap fails with the following error and  `gotk-sync.yaml` file is blank in GitOps repository :

```

```

`kustomization.yaml`

```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patchesStrategicMerge:
  - patch-gpg.yaml
```

`patch-gpg.yaml`
```
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  verify:
    mode: head
    secretRef:
      name: flux-gpg-pubkeys
```

However, it looks like if flux is already bootstrapped in the cluster and then we apply the patch , it works fine.

But this is not what we want. 

In previous versions of the provider (old bootstrap process), we were able to patch `GitRepository` during bootstrap itself using `patch_names` attribute of `flux_sync` resource.

Kindly suggest.

**Comment by stefanprodan** [comment]
See the docs https://registry.terraform.io/providers/fluxcd/flux/latest/docs/resources/bootstrap_git#customizing-flux

**Comment by anupclouddevops** [comment]
@stefanprodan I have already seen the docs and followed the same  . 

They talk about patching controllers etc. but not about GitRepository.

 But unfortunately GitRepository is not getting patched with this kustomozation_override method.

Could you please point out what I am doing wrong and how is my implementation different from what is mentioned in docs ?

**Comment by anupclouddevops** [comment]
@stefanprodan , I tried inline patch (removing namespace as well) but it gives the same error .

Could you please refer to an example where GitRepository is being patched during bootstrap process using the new resource?

**Comment by anupclouddevops** [comment]
@stefanprodan , could you please help with this ? I get the below error even when I use an inline patch?

│ Error: Bootstrap run error
│ 
│   with module.test-flux.flux_bootstrap_git.this,
│   on ../../main.tf line 8, in resource "flux_bootstrap_git" "this":
│    8: resource "flux_bootstrap_git" "this" {
│ 
│ no matches for Id
│ GitRepository.v1.source.toolkit.fluxcd.io/flux-system.flux-system; failed
│ to find unique target for patch
│ GitRepository.v1.source.toolkit.fluxcd.io/flux-system.flux-system
╵}

The pattern is clear :
- If flux is already bootstrapped and `GitRepository` resource is already created , then patching it works
- it fails with the above error during bootstrap as it's unable to find `GitRepository` resource.

Please help as it's a blocker for us to upgrade to the new bootstrap resource as we have GPG verification enabled in our Custers.

**Comment by somtochiama** [comment]
Hey @anupclouddevops ,
I tested with this patch on a fresh kind cluster and it worked okay
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      metadata:
        name: flux-system
        namespace: flux-system
      spec:
          verify:
            mode: head
            secretRef:
              name: flux-gpg-pubkeys
    target:
      kind: GitRepository
      name: flux-system
      namespace: flux-system
```

```
│ no matches for Id
│ GitRepository.v1.source.toolkit.fluxcd.io/flux-system.flux-system; failed
```
This error is from kustomize being unable to apply your patch.
What version of the terraform provider are you using. If you are on an older version, it will generate a `v1beta2` GitRepository manifest and the patch will fail since you are using `v1` version in the patch.
