### ISSUE TITLE
Toleration keys regex prevents adding "/"

### ISSUE THREAD

**Issue by fbueno** [fluxcd/terraform-provider-flux#578]
I'm running flux on Azure AKS which adds the `kubernetes.azure.com/scalesetpriority=spot:NoSchedule` taint to spot instances.

However, I can't add such key in `toleration_keys` in the flux provider.
I get the message:
```
│ Attribute toleration_keys[Value("kubernetes.azure.com/scalesetpriority")] a toleration key must begin with a letter or number, and may contain letters, numbers, hyphens, dots,
│ and underscores., got: kubernetes.azure.com/scalesetpriority
```

It seems that [this is the line](https://github.com/fluxcd/terraform-provider-flux/blob/main/internal/provider/resource_bootstrap_git.go#L83) that is preventing me doing that.

I wonder if I'm the first one having such issue as I don't see anyone mentioning it.

**Comment by stefanprodan** [comment]
You can add the toleration as patch in `kustomization.yaml`, docs here https://registry.terraform.io/providers/fluxcd/flux/latest/docs/resources/bootstrap_git#customizing-flux

**Comment by imishchuk-carbon** [comment]
In my case I'm using `~1` to represent `/`

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
      - op: add
        path: /spec/template/spec/nodeSelector/node-restriction.kubernetes.io~1reserved-for
        value: ...
```
