### ISSUE TITLE
Flux bootstrap does not change k8s resources

### ISSUE THREAD

**Issue by hirenko-v** [fluxcd/terraform-provider-flux#617]
### Describe the bug

I Have such config
```
resource "flux_bootstrap_git" "this" {
  path             = ./clusters/development
  version         = "v2.2.3"
  kustomization_override = templatefile("${path.module}/kustomization.tpl",
    {
      cluster_name = "development"
      environment  = "development"
    }
  )
}
```
After successful bootstrap I change kustomization.tpl and run terraform apply, I see changes in GIt but there are no changes in flux Kustomization resource in cluster

### Steps to reproduce

1. terraform apply
2. do some changes in kustomization_override file
2. terraform apply

### Expected behavior

flux kustomization reource in cluster has changed

### Terraform and provider versions

Terraform v1.6.6
Flux 1.2.3

### flux_bootstrap_git resource

```
resource "flux_bootstrap_git" "this" {
  path             = ./clusters/development
  version         = "v2.2.3"
  kustomization_override = templatefile("${path.module}/kustomization.tpl",
    {
      cluster_name = "development"
      environment  = "development"
    }
  )
}
```

### Flux version

v2.2.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by swade1987** [comment]
@hirenko-v, so to clarify:

1. When you perform a `plan` the changes are shown?
2. When you perform an `apply` the changes are visible in your git repo

However, the changes are not reconciled by flux from Git. Is this correct?

**Comment by hirenko-v** [comment]
@swade1987 , 
1. yes changes are shown I see that file is changed
2. after performing apply changes are visible in git but there are no changes in the real cluster

For example
![image](https://github.com/fluxcd/terraform-provider-flux/assets/132065511/7ca81206-09d6-46c7-a806-c16c87befa87)

![image](https://github.com/fluxcd/terraform-provider-flux/assets/132065511/e3602041-1c83-49ba-8974-2e6f02d97e19)

**Comment by swade1987** [comment]
Could you please share the complete `Kustomization` configuration you're applying with flux_bootstrap_git? It would be really helpful if you could highlight the specific line or section you've modified. Additionally, could you also provide a link or a screenshot of this change in your Git repository? I'm aiming to fully understand the adjustments you've made to ensure they align properly with the expected configurations. Thank you for being so cooperative.

**Comment by hirenko-v** [comment]
here is the kustomization.tpl file, once again, it is succesfully apied during first bootstrap but not updated in k8s during another apply
unfortunately, repo is private
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      - op: add
        path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/eventSources/items/properties/kind/enum/-
        value: Terraform
      - op: add
        path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/eventSources/items/properties/kind/enum/-
        value: Terraform
      - op: add
        path: /spec/versions/2/schema/openAPIV3Schema/properties/spec/properties/eventSources/items/properties/kind/enum/-
        value: Terraform
    target:
      kind: CustomResourceDefinition
      name:  alerts.notification.toolkit.fluxcd.io
  - patch: |
      - op: add
        path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/resources/items/properties/kind/enum/-
        value: Terraform
      - op: add
        path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/resources/items/properties/kind/enum/-
        value: Terraform
      - op: add
        path: /spec/versions/2/schema/openAPIV3Schema/properties/spec/properties/resources/items/properties/kind/enum/-
        value: Terraform
    target:
      kind: CustomResourceDefinition
      name:  receivers.notification.toolkit.fluxcd.io
  - patch: |
      - op: add
        path: /rules/-
        value:
          apiGroups: [ 'infra.contrib.fluxcd.io' ]
          resources: [ '*' ]
          verbs: [ '*' ]
    target:
      kind: ClusterRole
      name:  crd-controller-flux-system

  - patch: |
      - op: add
        path: /spec/postBuild
        value:
          substitute:
            cluster_name: ${cluster_name}
            tf_controller_sa_name: ${tf_sa_name}
            tf_controller_role_arn: ${tf_role_arn}
            environment: ${environment}
            iam_secret_name: eks-iam-${environment}
      - op: add
        path: /spec/healthChecks
        value:
        - apiVersion: helm.toolkit.fluxcd.io/v2beta2
          kind: HelmRelease
          name: tf-controller
          namespace: flux-system
    target:
      kind: Kustomization
      name:  flux-system

```

**Comment by swade1987** [comment]
@hirenko-v Which part was the change you made when you executed the second `terraform apply` ?

**Comment by stefanprodan** [comment]
@hirenko-v if the kustomization.yaml is updated in Git, then Flux will apply it on its own, it takes max one minute to do so.

**Comment by swade1987** [comment]
@hirenko-v I am unable to replicate this.

I used [this example](https://github.com/fluxcd/terraform-provider-flux/tree/main/examples/github-with-inline-customizations) and set the role_arn to `test-123`. The cluster bootstrapped correctly (see below).

```
❯ k get sa -n flux-system source-controller -o yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: test-123
  ....
```

I changed the `role_arn` to `test-456` in `variables.tf` and ran `terraform apply` (see output below)

<img width="794" alt="Screenshot 2024-03-27 at 20 06 26" src="https://github.com/fluxcd/terraform-provider-flux/assets/594451/606bc9d6-7103-4107-b21e-2002500abe4d">

The git commit can be seen [here](https://github.com/swade1987/flux-bootstrap/commit/23410caa691bfdb6ad7732f9cfc82550cc97020b)

The change in the cluster can be seen below

```

❯ k get sa -n flux-system source-controller -o yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: test-456
...
```

**Comment by swade1987** [comment]
I would be interested to see if this issue maybe related to https://github.com/fluxcd/terraform-provider-flux/issues/617#issuecomment-2023246283

**Comment by stefanprodan** [comment]
@swade1987 your test doesn't seem to replicate this issue, the problem is when the kustomization template changes without any changes in TF vars.

**Comment by swade1987** [comment]
> After successful bootstrap I change kustomization.tpl and run terraform apply, I see changes in GIt but there are no changes in flux Kustomization resource in cluster

I am not sure if this is true based upon

>After successful bootstrap **I change kustomization.tpl and run terraform apply**, I see changes in GIt but there are no changes in flux Kustomization resource in cluster

**Comment by swade1987** [comment]
@hirenko-v @stefanprodan  I am unable to replicate this.

I used [this example](https://github.com/fluxcd/terraform-provider-flux/tree/main/examples/github-with-inline-customizations) and set the role_arn to test-123. The cluster bootstrapped correctly (see below).

```
❯ k get sa -n flux-system kustomize-controller -o yaml | grep test
    eks.amazonaws.com/role-arn: test-123
```

I then added the following to the kustomization template:

```
  - patch: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: controller
        annotations:
          eks.amazonaws.com/role-arn: ${role_arn}
    target:
      kind: ServiceAccount
      name: "helm-controller"
```

The change was successfully committed to get via `terraform apply` see commit [here](https://github.com/swade1987/flux-bootstrap/commit/7c61ec87aa9d3c3377453bc5fbcdc2075f0da2c6)

This was then reflected in Kubernetes (see below)

```
❯ k get sa -n flux-system helm-controller -o yaml | grep test
    eks.amazonaws.com/role-arn: test-123
```
