### ISSUE TITLE
Automate issue/pull request stale process

### ISSUE THREAD

**Issue by swade1987** [fluxcd/terraform-provider-flux#624]
I would propose we just use something like the below. 

```
name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '10 3 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 9999
          days-before-close: 90
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          close-issue-message: |
            I will close this issue due to inactivity (_90 days_ without response ⏳ ). This helps our maintainers find and focus on the active issues.

            If this issue was automatically closed and you feel this issue should be reopened, we encourage you to create a new issue linking back to this one for added context. Thank you!

          close-pr-message: |
            I'm going to close this pull request due to inactivity (_90 days_ without response ⏳ ). This will help our maintainers find and focus on active contributions.

            If this pull request was automatically closed and you feel this pull request should be reopened, we would like to encourage you to create a new pull request linking back to this one for added context. Thank you!
```
