### ISSUE TITLE
kubernetes client initialization failed: no Auth Provider found for name "oidc"

### ISSUE THREAD

**Issue by kcighon** [fluxcd/terraform-provider-flux#669]
### Describe the bug

We use kubernetes on tkgi and authenticate against the cluster with sso to create our KUBECONFIG with 

- `tkgi login -a <tkgihostfqdn> -k -sso` 
- `export KUBECONFIG=~/.kube/<clustername>.yaml`
- `tkgi get-kubeconfig <clustername> -a <tkgihostfqdn> -k -sso`

The resultant KUBECONFIG looks like:

```yaml

apiVersion: v1
clusters: 
- cluster: 
      certificate-authority-data: xx....
      server: https://<myclusterfqdn>:8443 
  name: <clustername> 
contexts: 
- context: 
      cluster: <clustername> 
      user: <myoidcusername> 
   name: <clustername>
current-context: <clustername>
kind: Config
references: {}
users:
- name: <myoidcusername> 
   user: 
      auth-provider: 
         config: 
            client-id: pks_cluster_client 
            client-secret: "" 
            id-token: xx.... 
            idp-certificate-authority-data: xx.... 
            idp-issuer-url: https://<tkgihostfqdn>:8443/oauth/token
            refresh-token: xx.... 
         name: oidc 
```

Running terraform apply gives the error:

```bash
│ Error: Kubernetes Client 
│ 
│ with flux_bootstrap_git.this, 
│ on bootstrap.tf line 1, in resource "flux_bootstrap_git" "this": 
│ 1: resource "flux_bootstrap_git" "this" { 
│ 
│ kubernetes client initialization failed: no Auth Provider found for name "oidc" 

```

### Steps to reproduce

Our terraform code is as follows:

```terraform
terraform {
  required_providers {
    flux = {
      source = "fluxcd/flux"
      version = "1.2.3"
    }
  }
}

provider "flux" {
  kubernetes = {  }
  git = {
    url = var.git_url
    branch = var.git_branch
    
    # configure credentials
  }
}

resource "flux_bootstrap_git" "this" {
  path        = var.cluster_path
  registry   = var.registry
  version    = "v2.2.3"
}
```

### Expected behavior

With one of our TKGI clusters, this works as expected however the KUBECONFIG is token based only, not OIDC

### Terraform and provider versions

Terraform v1.7.3
fluxcd/flux Provider v1.2.3

### Terraform provider configurations

```terraform
terraform {
  required_providers {
    flux = {
      source = "fluxcd/flux"
      version = "1.2.3"
    }
  }
}

provider "flux" {
  kubernetes = {  }
  git = {
    url = var.git_url
    branch = var.git_branch
    
    # configure credentials
  }
}

```

### flux_bootstrap_git resource

```terraform


resource "flux_bootstrap_git" "this" {
  path        = var.cluster_path
  registry   = var.registry
  version    = "v2.2.3"
}
```

### Flux version

v2.2.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Would you like to implement a fix?

None

**Comment by swade1987** [comment]
@kcighon I have to admit I have never seen a kubeconfig with this block before 

```
 auth-provider: 
         config: 
            client-id: pks_cluster_client 
            client-secret: "" 
            id-token: xx.... 
            idp-certificate-authority-data: xx.... 
            idp-issuer-url: https://<tkgihostfqdn>:8443/oauth/token
            refresh-token: xx.... 
         name: oidc 
```

When using oidc to connect previously, I have seen the following:

```
users:
- name: keycloak
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: kubectl
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://issuer.example.com
      - --oidc-client-id=YOUR_CLIENT_ID
      - --oidc-client-secret=YOUR_CLIENT_SECRET
```

Are you able to use the kubeconfig snippet you provided an run `kubectl` commands without issues?
