### ISSUE TITLE
[Bug]: Source controller errors: failed to get credential from 'aws': failed to parse artifact repository nvalid AWS registry: 'public.ecr.aws'. must match

### ISSUE THREAD

**Issue by kappa8219** [fluxcd/terraform-provider-flux#763]
### Describe the bug

After upgrade with tf provider to 1.6.1 from 1.5.1 source controller fails to reconsile following:

```
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ack-controllers
  namespace: ack-system
spec:
  provider: aws
  interval: 1h
  type: oci
  url: oci://public.ecr.aws/aws-controllers-k8s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ack-controllers
  namespace: ack-system
spec:
  install:
    createNamespace: true
  chart:
    spec:
      chart: ack-chart
      version: 46.28.1
      sourceRef:
        kind: HelmRepository
        name: ack-controllers
  interval: 2m
  values:
```

the error is the same for all releases from oci://public.ecr.aws/aws-controllers-k8s, ex:

```
{
  "level": "error",
  "ts": "2025-06-02T09:21:31.157Z",
  "msg": "Reconciler error",
  "controller": "helmchart",
  "controllerGroup": "source.toolkit.fluxcd.io",
  "controllerKind": "HelmChart",
  "HelmChart": {
    "name": "ack-system-ack-route53-controller",
    "namespace": "ack-system"
  },
  "namespace": "ack-system",
  "name": "ack-system-ack-route53-controller",
  "reconcileID": "af8fa12b-e528-4057-ba61-477c7271199f",
  "error": "failed to get credential from aws: failed to parse artifact repository public.ecr.aws/aws-controllers-k8s: invalid AWS registry: public.ecr.aws. must match ([0-9+]*).dkr.ecr(?:-fips)?\\.([^/.]*)\\.(amazonaws\\.com[.cn]*|sc2s\\.sgov\\.gov|c2s\\.ic\\.gov|cloud\\.adc-e\\.uk|csp\\.hci\\.ic\\.gov)"
}
```

### Steps to reproduce

Upgrade with terraform provider

### Expected behavior

All fine

### Terraform and provider versions

```
tofu version
OpenTofu v1.9.1
on linux_amd64
+ provider registry.opentofu.org/fluxcd/flux v1.6.1
+ provider registry.opentofu.org/gitlabhq/gitlab v17.11.0
+ provider registry.opentofu.org/hashicorp/aws v5.99.1
+ provider registry.opentofu.org/hashicorp/awscc v1.43.0
+ provider registry.opentofu.org/hashicorp/kubernetes v2.37.1
+ provider registry.opentofu.org/hashicorp/null v3.2.4
+ provider registry.opentofu.org/hashicorp/tls v4.1.0
```

### Terraform provider configurations

```
provider "flux" {
  kubernetes = {
    host                   = data.terraform_remote_state.root_layer.outputs.cluster_endpoint
    cluster_ca_certificate = base64decode(data.terraform_remote_state.root_layer.outputs.cluster_certificate_authority_data)
    exec = {
      api_version = "client.authentication.k8s.io/v1beta1"
      args        = ["eks", "get-token", "--cluster-name", data.terraform_remote_state.root_layer.outputs.cluster_name]
      command     = "aws"
    }
  }
  git = {
    url = "https://gitlab.something.com/${var.gitlab_group}/${var.gitlab_project}"
    http = {
      username = "GitLab token"
      password = "${var.gitlab_token}"
    }
    branch = "master"
  }
}
```

### flux_bootstrap_git resource

```
resource "flux_bootstrap_git" "this" {
  depends_on = [gitlab_deploy_key.this]

  path = "cluster/xxxxx"
  toleration_keys = ["ng"]

}
```

### Flux version

nothing

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Would you like to implement a fix?

None
