### ISSUE TITLE
data.flux_install source ignores version parameter

### ISSUE THREAD

**Issue by vglafirov** [fluxcd/terraform-provider-flux#79]
I would like to lock the version of flux2 installed, to avoid accidental and uncontrolled updates. But whatever you specify in the `version` parameter is ignored :( 
Provider tries to recreate the whole flux-system namespace every new release hits fluxcd/flux2 repository.

```
data "flux_install" "flux_install_cluster" {
  target_path = "clusters/${var.environment}/${var.aws_region}/${var.name}"
  version     = "0.5.9" # Tried with "v0.5.9" with same result. 
}
```

some plan excert:

```
      ~ content             = <<~EOT
            apiVersion: v1
            kind: Namespace
            metadata:
              labels:
                app.kubernetes.io/instance: flux-system
          -     app.kubernetes.io/version: 0.5.9
          +     app.kubernetes.io/version: 0.6.22
              name: flux-system
            ---
            apiVersion: apiextensions.k8s.io/v1
            kind: CustomResourceDefinition
            metadata:
              annotations:
                controller-gen.kubebuilder.io/version: v0.3.0
              creationTimestamp: null
              labels:
                app.kubernetes.io/instance: flux-system
          -     app.kubernetes.io/version: 0.5.9
          +     app.kubernetes.io/version: 0.6.22
              name: alerts.notification.toolkit.fluxcd.io
```
